version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - NEXT_PUBLIC_API_URL=http://localhost:8000  # フロントエンドからバックエンドにアクセスするためのURL
    restart: unless-stopped
    # 開発時は以下のコメントを外すとホットリロードが有効になります
    # command: uvicorn api.backend:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000  # バックエンドのURL
    depends_on:
      - backend
    restart: unless-stopped
    # 開発時は以下のコメントを外すとホットリロードが有効になります
    # command: sh -c "npm install && npm run dev"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
